
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

-- Load all modules
require("modules.env")
require("modules.monitor")
require("modules.monitors-state")
require("modules.input")
require("modules.decorations")
require("modules.animations")
require("modules.layout")
require("modules.keybinds")
require("modules.binds")
require("modules.windowrules")
require("modules.plugins")
require("modules.misc")
require("modules.autostart")
require("modules.programs")

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})